# apps/inventory/urls/inventory_urls.py

from django.urls import path
from apps.inventory.views import (
    asset_audits_view,
    asset_condition_view,
    asset_directory_options_view,
    asset_correct_view,
    asset_custodies_view,
    asset_detail_view,
    asset_extended_record_view,
    asset_external_activity_view,
    asset_disposals_view,
    asset_documents_view,
    asset_financials_view,
    asset_history_view,
    asset_list_view,
    asset_loan_create_view,
    asset_loans_view,
    asset_movements_view,
    asset_photos_view,
    asset_technical_view,
    asset_technical_sheet_view,
    catalog_create_view,
    catalog_deactivate_view,
    catalog_list_view,
    catalog_update_view,
    custody_accept_view,
    custody_asset_options_view,
    custody_authorize_view,
    custody_cancel_view,
    custody_complete_return_view,
    custody_create_view,
    custody_document_close_view,
    custody_document_create_view,
    custody_document_detail_view,
    custody_document_list_view,
    custody_document_print_view,
    custody_document_replace_view,
    custody_deliver_view,
    custody_directory_areas_view,
    custody_directory_departments_view,
    custody_directory_users_view,
    custody_detail_view,
    custody_list_view,
    custody_print_view,
    custody_reject_view,
    custody_request_return_view,
    custody_submit_view,
    custody_signed_upload_view,
    disposal_detail_view,
    disposal_cancel_view,
    disposal_create_view,
    disposal_execute_view,
    disposal_finalize_view,
    disposal_list_view,
    disposal_resolve_stage_view,
    disposal_submit_view,
    disposal_stage_document_upload_view,
    disposal_document_validate_view,
    document_list_view,
    document_upload_view,
    document_download_view,
    document_validate_view,
    financial_dashboard_view,
    financial_history_view,
    accounting_export_create_view,
    accounting_export_download_view,
    depreciation_run_calculate_view,
    depreciation_run_create_view,
    depreciation_run_detail_view,
    depreciation_run_post_view,
    depreciation_policy_list_view,
    depreciation_policy_create_view,
    depreciation_policy_close_view,
    reconciliation_create_view,
    reconciliation_detail_view,
    reconciliation_process_view,
    reconciliation_close_view,
    intake_approve_view,
    intake_cancel_view,
    intake_create_view,
    intake_department_decision_view,
    intake_directory_areas_view,
    intake_directory_departments_view,
    intake_directory_users_view,
    intake_models_view,
    intake_detail_view,
    intake_list_view,
    intake_observe_view,
    intake_register_view,
    intake_send_to_patrimony_view,
    intake_submit_view,
    inventory_dashboard_view,
    inventory_help_detail_view,
    inventory_help_view,
    loan_authorize_view,
    loan_cancel_view,
    loan_create_view,
    loan_deliver_view,
    loan_department_decision_view,
    loan_directory_areas_view,
    loan_directory_assets_view,
    loan_directory_departments_view,
    loan_directory_users_view,
    loan_detail_view,
    loan_list_view,
    loan_print_view,
    loan_request_return_view,
    loan_return_view,
    loan_submit_view,
    movement_detail_view,
    movement_create_view,
    movement_directory_options_view,
    movement_request_detail_view,
    movement_origin_decision_view,
    movement_destination_decision_view,
    movement_execute_view,
    movement_list_view,
    physical_audit_detail_view,
    physical_audit_cancel_view,
    physical_audit_close_view,
    physical_audit_create_view,
    physical_audit_directory_areas_view,
    physical_audit_directory_departments_view,
    physical_audit_directory_users_view,
    physical_audit_eligible_assets_view,
    physical_audit_freeze_view,
    physical_audit_item_reconcile_view,
    physical_audit_list_view,
    physical_audit_not_found_view,
    physical_audit_pending_not_found_view,
    physical_audit_document_upload_view,
    physical_audit_photo_upload_view,
    physical_audit_report_view,
    physical_audit_reconciliation_view,
    physical_audit_scan_view,
    physical_audit_start_view,
    physical_audit_unlisted_view,
)

app_name = "inventory"

urlpatterns = [
    # Panel principal
    path("", inventory_dashboard_view, name="dashboard"),

    # Catálogos institucionales de Inventory
    path("catalogs/", catalog_list_view, name="catalog_home"),
    path("catalogs/<slug:catalog>/", catalog_list_view, name="catalog_list"),
    path("catalogs/<slug:catalog>/new/", catalog_create_view, name="catalog_create"),
    path("catalogs/<slug:catalog>/<uuid:entry_id>/edit/", catalog_update_view, name="catalog_update"),
    path("catalogs/<slug:catalog>/<uuid:entry_id>/deactivate/", catalog_deactivate_view, name="catalog_deactivate"),

    # Activos patrimoniales
    path("assets/", asset_list_view, name="asset_list"),
    path("assets/directory/options/", asset_directory_options_view, name="asset_directory_options"),
    path("assets/<uuid:asset_id>/", asset_detail_view, name="asset_detail"),
    path("assets/<uuid:asset_id>/technical/", asset_technical_view, name="asset_technical"),
    path("assets/<uuid:asset_id>/custodies/", asset_custodies_view, name="asset_custodies"),
    path("assets/<uuid:asset_id>/loans/", asset_loans_view, name="asset_loans"),
    path("assets/<uuid:asset_id>/movements/", asset_movements_view, name="asset_movements"),
    path("assets/<uuid:asset_id>/external-activity/", asset_external_activity_view, name="asset_external_activity"),
    path("assets/<uuid:asset_id>/documents/", asset_documents_view, name="asset_documents"),
    path("assets/<uuid:asset_id>/photos/", asset_photos_view, name="asset_photos"),
    path("assets/<uuid:asset_id>/financials/", asset_financials_view, name="asset_financials"),
    path("assets/<uuid:asset_id>/audits/", asset_audits_view, name="asset_audits"),
    path("assets/<uuid:asset_id>/disposals/", asset_disposals_view, name="asset_disposals"),
    path("assets/<uuid:asset_id>/history/", asset_history_view, name="asset_history"),
    path("assets/<uuid:asset_id>/correct/", asset_correct_view, name="asset_correct"),
    path("assets/<uuid:asset_id>/condition/", asset_condition_view, name="asset_condition"),
    path("assets/<uuid:asset_id>/loan/", asset_loan_create_view, name="asset_loan_create"),
    path("assets/<uuid:asset_id>/technical-sheet/", asset_technical_sheet_view, name="asset_technical_sheet"),
    path("assets/<uuid:asset_id>/extended-record/", asset_extended_record_view, name="asset_extended_record"),

    # Solicitudes de alta (Intakes)
    path("intakes/", intake_list_view, name="intake_list"),
    path("intakes/new/", intake_create_view, name="intake_create"),
    path("intakes/directory/departments/", intake_directory_departments_view, name="intake_directory_departments"),
    path("intakes/directory/areas/", intake_directory_areas_view, name="intake_directory_areas"),
    path("intakes/directory/users/", intake_directory_users_view, name="intake_directory_users"),
    path("intakes/catalog/models/", intake_models_view, name="intake_models"),
    path("intakes/<uuid:intake_id>/", intake_detail_view, name="intake_detail"),
    path("intakes/<uuid:intake_id>/submit/", intake_submit_view, name="intake_submit"),
    path("intakes/<uuid:intake_id>/department-decision/", intake_department_decision_view, name="intake_department_decision"),
    path("intakes/<uuid:intake_id>/send-to-patrimony/", intake_send_to_patrimony_view, name="intake_send_to_patrimony"),
    path("intakes/<uuid:intake_id>/observe/", intake_observe_view, name="intake_observe"),
    path("intakes/<uuid:intake_id>/approve/", intake_approve_view, name="intake_approve"),
    path("intakes/<uuid:intake_id>/register/", intake_register_view, name="intake_register"),
    path("intakes/<uuid:intake_id>/cancel/", intake_cancel_view, name="intake_cancel"),

    # Resguardos
    path("custodies/", custody_list_view, name="custody_list"),
    path("custodies/new/", custody_create_view, name="custody_create"),
    path("custodies/documents/", custody_document_list_view, name="custody_document_list"),
    path("custodies/documents/new/", custody_document_create_view, name="custody_document_create"),
    path("custodies/documents/<uuid:document_id>/", custody_document_detail_view, name="custody_document_detail"),
    path("custodies/documents/<uuid:document_id>/print/", custody_document_print_view, name="custody_document_print"),
    path("custodies/documents/<uuid:document_id>/close/", custody_document_close_view, name="custody_document_close"),
    path("custodies/documents/<uuid:document_id>/replace/", custody_document_replace_view, name="custody_document_replace"),
    path("custodies/directory/assets/", custody_asset_options_view, name="custody_asset_options"),
    path("custodies/directory/departments/", custody_directory_departments_view, name="custody_directory_departments"),
    path("custodies/directory/areas/", custody_directory_areas_view, name="custody_directory_areas"),
    path("custodies/directory/users/", custody_directory_users_view, name="custody_directory_users"),
    path("custodies/<uuid:custody_id>/", custody_detail_view, name="custody_detail"),
    path("custodies/<uuid:custody_id>/print/", custody_print_view, name="custody_print"),
    path("custodies/<uuid:custody_id>/signed-document/", custody_signed_upload_view, name="custody_signed_upload"),
    path("custodies/<uuid:custody_id>/submit/", custody_submit_view, name="custody_submit"),
    path("custodies/<uuid:custody_id>/authorize/", custody_authorize_view, name="custody_authorize"),
    path("custodies/<uuid:custody_id>/deliver/", custody_deliver_view, name="custody_deliver"),
    path("custodies/<uuid:custody_id>/accept/", custody_accept_view, name="custody_accept"),
    path("custodies/<uuid:custody_id>/reject/", custody_reject_view, name="custody_reject"),
    path("custodies/<uuid:custody_id>/request-return/", custody_request_return_view, name="custody_request_return"),
    path("custodies/<uuid:custody_id>/complete-return/", custody_complete_return_view, name="custody_complete_return"),
    path("custodies/<uuid:custody_id>/cancel/", custody_cancel_view, name="custody_cancel"),

    # Movimientos patrimoniales
    path("movements/", movement_list_view, name="movement_list"),
    path("movements/new/<str:movement_kind>/", movement_create_view, name="movement_create"),
    path("movements/directory/options/", movement_directory_options_view, name="movement_directory_options"),
    path("movements/requests/<uuid:request_id>/", movement_request_detail_view, name="movement_request_detail"),
    path("movements/requests/<uuid:request_id>/origin-decision/", movement_origin_decision_view, name="movement_origin_decision"),
    path("movements/requests/<uuid:request_id>/destination-decision/", movement_destination_decision_view, name="movement_destination_decision"),
    path("movements/requests/<uuid:request_id>/execute/", movement_execute_view, name="movement_execute"),
    path("movements/<uuid:movement_id>/", movement_detail_view, name="movement_detail"),

    # Préstamos
    path("loans/", loan_list_view, name="loan_list"),
    path("loans/new/", loan_create_view, name="loan_create"),
    path("loans/directory/departments/", loan_directory_departments_view, name="loan_directory_departments"),
    path("loans/directory/areas/", loan_directory_areas_view, name="loan_directory_areas"),
    path("loans/directory/users/", loan_directory_users_view, name="loan_directory_users"),
    path("loans/directory/assets/", loan_directory_assets_view, name="loan_directory_assets"),
    path("loans/<uuid:loan_id>/", loan_detail_view, name="loan_detail"),
    path("loans/<uuid:loan_id>/print/", loan_print_view, name="loan_print"),
    path("loans/<uuid:loan_id>/submit/", loan_submit_view, name="loan_submit"),
    path("loans/<uuid:loan_id>/department-decision/", loan_department_decision_view, name="loan_department_decision"),
    path("loans/<uuid:loan_id>/authorize/", loan_authorize_view, name="loan_authorize"),
    path("loans/<uuid:loan_id>/deliver/", loan_deliver_view, name="loan_deliver"),
    path("loans/<uuid:loan_id>/request-return/", loan_request_return_view, name="loan_request_return"),
    path("loans/<uuid:loan_id>/return/", loan_return_view, name="loan_return"),
    path("loans/<uuid:loan_id>/cancel/", loan_cancel_view, name="loan_cancel"),

    # Bajas patrimoniales
    path("disposals/", disposal_list_view, name="disposal_list"),
    path("disposals/new/", disposal_create_view, name="disposal_create"),
    path("disposals/<uuid:disposal_id>/", disposal_detail_view, name="disposal_detail"),
    path("disposals/<uuid:disposal_id>/submit/", disposal_submit_view, name="disposal_submit"),
    path("disposals/<uuid:disposal_id>/resolve-stage/", disposal_resolve_stage_view, name="disposal_resolve_stage"),
    path("disposals/<uuid:disposal_id>/finalize/", disposal_finalize_view, name="disposal_finalize"),
    path("disposals/<uuid:disposal_id>/execute/", disposal_execute_view, name="disposal_execute"),
    path("disposals/<uuid:disposal_id>/cancel/", disposal_cancel_view, name="disposal_cancel"),
    path("disposals/<uuid:disposal_id>/stages/<uuid:approval_id>/documents/new/", disposal_stage_document_upload_view, name="disposal_stage_document_upload"),
    path("disposals/<uuid:disposal_id>/documents/<uuid:document_id>/validate/", disposal_document_validate_view, name="disposal_document_validate"),

    # Documentos y evidencias
    path("documents/", document_list_view, name="document_list"),
    path("documents/new/<str:owner_type>/<uuid:owner_id>/", document_upload_view, name="document_upload"),
    path("documents/<uuid:document_id>/open/", document_download_view, name="document_download"),
    path("documents/<uuid:document_id>/validate/", document_validate_view, name="document_validate"),

    # Auditoría física
    path("physical-audits/", physical_audit_list_view, name="physical_audit_list"),
    path("physical-audits/directory/departments/", physical_audit_directory_departments_view, name="physical_audit_directory_departments"),
    path("physical-audits/directory/areas/", physical_audit_directory_areas_view, name="physical_audit_directory_areas"),
    path("physical-audits/directory/users/", physical_audit_directory_users_view, name="physical_audit_directory_users"),
    path("physical-audits/directory/eligible-assets/", physical_audit_eligible_assets_view, name="physical_audit_eligible_assets"),
    path("physical-audits/new/", physical_audit_create_view, name="physical_audit_create"),
    path("physical-audits/<uuid:session_id>/", physical_audit_detail_view, name="physical_audit_detail"),
    path("physical-audits/<uuid:session_id>/freeze/", physical_audit_freeze_view, name="physical_audit_freeze"),
    path("physical-audits/<uuid:session_id>/start/", physical_audit_start_view, name="physical_audit_start"),
    path("physical-audits/<uuid:session_id>/scan/", physical_audit_scan_view, name="physical_audit_scan"),
    path("physical-audits/<uuid:session_id>/unlisted/", physical_audit_unlisted_view, name="physical_audit_unlisted"),
    path("physical-audits/<uuid:session_id>/pending/not-found/", physical_audit_pending_not_found_view, name="physical_audit_pending_not_found"),
    path("physical-audits/<uuid:session_id>/documents/new/", physical_audit_document_upload_view, name="physical_audit_document_upload"),
    path("physical-audits/<uuid:session_id>/photos/new/", physical_audit_photo_upload_view, name="physical_audit_photo_upload"),
    path("physical-audits/<uuid:session_id>/report/", physical_audit_report_view, name="physical_audit_report"),
    path("physical-audits/<uuid:session_id>/reconciliation/", physical_audit_reconciliation_view, name="physical_audit_reconciliation"),
    path("physical-audits/<uuid:session_id>/items/<uuid:item_id>/not-found/", physical_audit_not_found_view, name="physical_audit_not_found"),
    path("physical-audits/<uuid:session_id>/items/<uuid:item_id>/reconcile/", physical_audit_item_reconcile_view, name="physical_audit_item_reconcile"),
    path("physical-audits/<uuid:session_id>/items/<uuid:item_id>/documents/new/", physical_audit_document_upload_view, name="physical_audit_item_document_upload"),
    path("physical-audits/<uuid:session_id>/items/<uuid:item_id>/photos/new/", physical_audit_photo_upload_view, name="physical_audit_item_photo_upload"),
    path("physical-audits/<uuid:session_id>/close/", physical_audit_close_view, name="physical_audit_close"),
    path("physical-audits/<uuid:session_id>/cancel/", physical_audit_cancel_view, name="physical_audit_cancel"),

    # Finanzas y conciliación
    path("financials/", financial_dashboard_view, name="financial_dashboard"),
    path("financials/history/<slug:section>/", financial_history_view, name="financial_history"),
    path("financials/depreciation/new/", depreciation_run_create_view, name="depreciation_run_create"),
    path("financials/depreciation/policies/", depreciation_policy_list_view, name="depreciation_policy_list"),
    path("financials/depreciation/policies/new/", depreciation_policy_create_view, name="depreciation_policy_create"),
    path("financials/depreciation/policies/<uuid:policy_id>/close/", depreciation_policy_close_view, name="depreciation_policy_close"),
    path("financials/depreciation/<uuid:run_id>/", depreciation_run_detail_view, name="depreciation_run_detail"),
    path("financials/depreciation/<uuid:run_id>/calculate/", depreciation_run_calculate_view, name="depreciation_run_calculate"),
    path("financials/depreciation/<uuid:run_id>/post/", depreciation_run_post_view, name="depreciation_run_post"),
    path("financials/exports/new/", accounting_export_create_view, name="accounting_export_create"),
    path("financials/exports/<uuid:batch_id>/download/", accounting_export_download_view, name="accounting_export_download"),
    path("financials/reconciliations/new/", reconciliation_create_view, name="reconciliation_create"),
    path("financials/reconciliations/<uuid:reconciliation_id>/", reconciliation_detail_view, name="reconciliation_detail"),
    path("financials/reconciliations/<uuid:reconciliation_id>/process/", reconciliation_process_view, name="reconciliation_process"),
    path("financials/reconciliations/<uuid:reconciliation_id>/close/", reconciliation_close_view, name="reconciliation_close"),

    # Centro de ayuda y flujos funcionales
    path("help/", inventory_help_view, name="help"),
    path("help/<slug:workflow_code>/", inventory_help_detail_view, name="help_detail"),
]
