# apps/inventory/urls/inventory_urls.py

from django.urls import path
from apps.inventory.views import (
    asset_audits_view,
    asset_condition_view,
    asset_correct_view,
    asset_custodies_view,
    asset_detail_view,
    asset_extended_record_view,
    asset_disposals_view,
    asset_documents_view,
    asset_financials_view,
    asset_history_view,
    asset_list_view,
    asset_loan_create_view,
    asset_loans_view,
    asset_movements_view,
    asset_photos_view,
    asset_technical_view,
    asset_technical_sheet_view,
    custody_accept_view,
    custody_authorize_view,
    custody_cancel_view,
    custody_complete_return_view,
    custody_create_view,
    custody_deliver_view,
    custody_directory_areas_view,
    custody_directory_departments_view,
    custody_directory_users_view,
    custody_detail_view,
    custody_list_view,
    custody_reject_view,
    custody_request_return_view,
    custody_submit_view,
    disposal_detail_view,
    disposal_list_view,
    document_list_view,
    financial_dashboard_view,
    intake_approve_view,
    intake_cancel_view,
    intake_create_view,
    intake_department_decision_view,
    intake_directory_areas_view,
    intake_directory_departments_view,
    intake_directory_users_view,
    intake_detail_view,
    intake_list_view,
    intake_observe_view,
    intake_register_view,
    intake_send_to_patrimony_view,
    intake_submit_view,
    inventory_dashboard_view,
    inventory_help_detail_view,
    inventory_help_view,
    loan_authorize_view,
    loan_cancel_view,
    loan_create_view,
    loan_deliver_view,
    loan_department_decision_view,
    loan_directory_areas_view,
    loan_directory_assets_view,
    loan_directory_departments_view,
    loan_directory_users_view,
    loan_detail_view,
    loan_list_view,
    loan_request_return_view,
    loan_return_view,
    loan_submit_view,
    movement_detail_view,
    movement_list_view,
    physical_audit_detail_view,
    physical_audit_list_view,
)

app_name = "inventory"

urlpatterns = [
    # Panel principal
    path("", inventory_dashboard_view, name="dashboard"),

    # Activos patrimoniales
    path("assets/", asset_list_view, name="asset_list"),
    path("assets/<uuid:asset_id>/", asset_detail_view, name="asset_detail"),
    path("assets/<uuid:asset_id>/technical/", asset_technical_view, name="asset_technical"),
    path("assets/<uuid:asset_id>/custodies/", asset_custodies_view, name="asset_custodies"),
    path("assets/<uuid:asset_id>/loans/", asset_loans_view, name="asset_loans"),
    path("assets/<uuid:asset_id>/movements/", asset_movements_view, name="asset_movements"),
    path("assets/<uuid:asset_id>/documents/", asset_documents_view, name="asset_documents"),
    path("assets/<uuid:asset_id>/photos/", asset_photos_view, name="asset_photos"),
    path("assets/<uuid:asset_id>/financials/", asset_financials_view, name="asset_financials"),
    path("assets/<uuid:asset_id>/audits/", asset_audits_view, name="asset_audits"),
    path("assets/<uuid:asset_id>/disposals/", asset_disposals_view, name="asset_disposals"),
    path("assets/<uuid:asset_id>/history/", asset_history_view, name="asset_history"),
    path("assets/<uuid:asset_id>/correct/", asset_correct_view, name="asset_correct"),
    path("assets/<uuid:asset_id>/condition/", asset_condition_view, name="asset_condition"),
    path("assets/<uuid:asset_id>/loan/", asset_loan_create_view, name="asset_loan_create"),
    path("assets/<uuid:asset_id>/technical-sheet/", asset_technical_sheet_view, name="asset_technical_sheet"),
    path("assets/<uuid:asset_id>/extended-record/", asset_extended_record_view, name="asset_extended_record"),

    # Solicitudes de alta (Intakes)
    path("intakes/", intake_list_view, name="intake_list"),
    path("intakes/new/", intake_create_view, name="intake_create"),
    path("intakes/directory/departments/", intake_directory_departments_view, name="intake_directory_departments"),
    path("intakes/directory/areas/", intake_directory_areas_view, name="intake_directory_areas"),
    path("intakes/directory/users/", intake_directory_users_view, name="intake_directory_users"),
    path("intakes/<uuid:intake_id>/", intake_detail_view, name="intake_detail"),
    path("intakes/<uuid:intake_id>/submit/", intake_submit_view, name="intake_submit"),
    path("intakes/<uuid:intake_id>/department-decision/", intake_department_decision_view, name="intake_department_decision"),
    path("intakes/<uuid:intake_id>/send-to-patrimony/", intake_send_to_patrimony_view, name="intake_send_to_patrimony"),
    path("intakes/<uuid:intake_id>/observe/", intake_observe_view, name="intake_observe"),
    path("intakes/<uuid:intake_id>/approve/", intake_approve_view, name="intake_approve"),
    path("intakes/<uuid:intake_id>/register/", intake_register_view, name="intake_register"),
    path("intakes/<uuid:intake_id>/cancel/", intake_cancel_view, name="intake_cancel"),

    # Resguardos
    path("custodies/", custody_list_view, name="custody_list"),
    path("custodies/new/", custody_create_view, name="custody_create"),
    path("custodies/directory/departments/", custody_directory_departments_view, name="custody_directory_departments"),
    path("custodies/directory/areas/", custody_directory_areas_view, name="custody_directory_areas"),
    path("custodies/directory/users/", custody_directory_users_view, name="custody_directory_users"),
    path("custodies/<uuid:custody_id>/", custody_detail_view, name="custody_detail"),
    path("custodies/<uuid:custody_id>/submit/", custody_submit_view, name="custody_submit"),
    path("custodies/<uuid:custody_id>/authorize/", custody_authorize_view, name="custody_authorize"),
    path("custodies/<uuid:custody_id>/deliver/", custody_deliver_view, name="custody_deliver"),
    path("custodies/<uuid:custody_id>/accept/", custody_accept_view, name="custody_accept"),
    path("custodies/<uuid:custody_id>/reject/", custody_reject_view, name="custody_reject"),
    path("custodies/<uuid:custody_id>/request-return/", custody_request_return_view, name="custody_request_return"),
    path("custodies/<uuid:custody_id>/complete-return/", custody_complete_return_view, name="custody_complete_return"),
    path("custodies/<uuid:custody_id>/cancel/", custody_cancel_view, name="custody_cancel"),

    # Movimientos patrimoniales
    path("movements/", movement_list_view, name="movement_list"),
    path("movements/<uuid:movement_id>/", movement_detail_view, name="movement_detail"),

    # Préstamos
    path("loans/", loan_list_view, name="loan_list"),
    path("loans/new/", loan_create_view, name="loan_create"),
    path("loans/directory/departments/", loan_directory_departments_view, name="loan_directory_departments"),
    path("loans/directory/areas/", loan_directory_areas_view, name="loan_directory_areas"),
    path("loans/directory/users/", loan_directory_users_view, name="loan_directory_users"),
    path("loans/directory/assets/", loan_directory_assets_view, name="loan_directory_assets"),
    path("loans/<uuid:loan_id>/", loan_detail_view, name="loan_detail"),
    path("loans/<uuid:loan_id>/submit/", loan_submit_view, name="loan_submit"),
    path("loans/<uuid:loan_id>/department-decision/", loan_department_decision_view, name="loan_department_decision"),
    path("loans/<uuid:loan_id>/authorize/", loan_authorize_view, name="loan_authorize"),
    path("loans/<uuid:loan_id>/deliver/", loan_deliver_view, name="loan_deliver"),
    path("loans/<uuid:loan_id>/request-return/", loan_request_return_view, name="loan_request_return"),
    path("loans/<uuid:loan_id>/return/", loan_return_view, name="loan_return"),
    path("loans/<uuid:loan_id>/cancel/", loan_cancel_view, name="loan_cancel"),

    # Bajas patrimoniales
    path("disposals/", disposal_list_view, name="disposal_list"),
    path("disposals/<uuid:disposal_id>/", disposal_detail_view, name="disposal_detail"),

    # Documentos y evidencias
    path("documents/", document_list_view, name="document_list"),

    # Auditoría física
    path("physical-audits/", physical_audit_list_view, name="physical_audit_list"),
    path("physical-audits/<uuid:session_id>/", physical_audit_detail_view, name="physical_audit_detail"),

    # Finanzas y conciliación
    path("financials/", financial_dashboard_view, name="financial_dashboard"),

    # Centro de ayuda y flujos funcionales
    path("help/", inventory_help_view, name="help"),
    path("help/<slug:workflow_code>/", inventory_help_detail_view, name="help_detail"),
]
