services:
  db_dev:
    image: postgres:15-alpine
    container_name: axentra_postgres_wsl_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass_dev_wsl
      POSTGRES_DB: axentra_core_docker
    volumes:
      - postgres_wsl_dev_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432" # Expuesto por si quieres auditar la BD con DBeaver o TablePlus
    networks:
      - axentra-wsl-network

  web_dev:
    build: .
    container_name: axentra_app_wsl_dev
    # Usamos runserver nativo para capturar cambios de código al vuelo sin recompilar
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=docker
      - DJANGO_SETTINGS_MODULE=core.settings.development
    env_file:
      - .env.docker
    depends_on:
      - db_dev
    networks:
      - axentra-wsl-network

volumes:
  postgres_wsl_dev_data:

networks:
  axentra-wsl-network:
    driver: bridge