# Generated by Django 6.0.6 on 2026-07-08 21:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='¿Está Eliminado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja Lógica')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Módulo')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador Técnico')),
                ('description', models.TextField(blank=True, verbose_name='Descripción Operativa')),
            ],
            options={
                'verbose_name': 'Módulo Instalado',
                'verbose_name_plural': 'Módulos Instalados',
                'db_table': 'axentra_sec_modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='¿Está Eliminado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja Lógica')),
                ('app_name', models.CharField(default='GovStack', max_length=50, verbose_name='Nombre del Sistema')),
                ('entidad_nombre', models.CharField(default='H. Ayuntamiento Constitucional', max_length=150, verbose_name='Nombre del Ayuntamiento / Institución')),
                ('siglas', models.CharField(default='GOV', max_length=15, verbose_name='Siglas de la Entidad')),
                ('direccion_oficial', models.TextField(blank=True, verbose_name='Dirección Institucional Sede')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC de la Institución')),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='institucion/logos/', verbose_name='Escudo Oficial (Fondo Claro)')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='institucion/logos/', verbose_name='Escudo Oficial (Fondo Oscuro)')),
                ('primary_color_class', models.CharField(default='slate-950', help_text='Clase nativa de Tailwind para branding.', max_length=30, verbose_name='Color de Acento (Tailwind Class)')),
            ],
            options={
                'verbose_name': 'Configuración Institucional',
                'verbose_name_plural': 'Configuraciones Institucionales',
                'db_table': 'axentra_core_tenant_config',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('must_change_password', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_manager', models.BooleanField(default=False, help_text='Indica si el usuario cuenta con inmunidad jerárquica y bypass global.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'axentra_core_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='¿Está Eliminado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja Lógica')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Dependencia')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('encargado_departamento', models.ForeignKey(blank=True, help_text='Director o Jefe de Área con facultades para gestionar su personal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependencias_administrativas_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Titular / Encargado de la Dependencia')),
            ],
            options={
                'verbose_name': 'Dependencia / Dirección',
                'verbose_name_plural': 'Dependencias / Direcciones',
                'db_table': 'axentra_org_dependencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AreaOperativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='¿Está Eliminado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja Lógica')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Oficina / Área')),
                ('slug', models.SlugField(editable=False, max_length=150)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='security.dependencia', verbose_name='Dependencia Superior')),
            ],
            options={
                'verbose_name': 'Área Operativa / Oficina',
                'verbose_name_plural': 'Áreas Operativas / Oficinas',
                'db_table': 'axentra_org_areas_operativas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('app_namespace', models.CharField(db_index=True, default='core', max_length=50, verbose_name='Ecosistema / App')),
                ('action_type', models.CharField(choices=[('CREATE', '➕ ALTA / CREACIÓN'), ('UPDATE', '📝 MODIFICACIÓN / ACTUALIZACIÓN'), ('DELETE', '❌ BAJA / ELIMINACIÓN'), ('ASSIGN', '🔑 ASIGNACIÓN / PRIVILEGIO'), ('ACCESS', '🔓 ACCESO / LOGIN / CONTROL'), ('QUERY', '🔍 CONSULTA / EXTRACCIÓN FORENSE'), ('RESET', '🔒 RESTABLECIMIENTO / LOCKDOWN')], db_index=True, default='UPDATE', max_length=20, verbose_name='Tipo de Acción (Verbo)')),
                ('module_component', models.CharField(db_index=True, default='GENERAL', max_length=100, verbose_name='Componente / Vista de Origen')),
                ('level_status', models.CharField(choices=[('CRITICAL', '🚨 Operación Crítica / Traslape / Bloqueo'), ('SUCCESS', '🟢 Operación Exitosa / Acceso Concedido'), ('INFO', '🔵 Modificación Informativa / Rutina')], db_index=True, default='INFO', max_length=15, verbose_name='Nivel del Evento')),
                ('action_name', models.CharField(db_index=True, max_length=150, verbose_name='Descripción de la Acción')),
                ('search_target', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Criterio / Llave de Búsqueda Dinámica')),
                ('target_scope', models.CharField(max_length=255, verbose_name='Ámbito / Descripción del Destino')),
                ('ip_address', models.GenericIPAddressField(db_index=True, default='127.0.0.1', verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Navegador / Dispositivo')),
                ('payload_json', models.JSONField(blank=True, default=dict, verbose_name='Telemetría Estructurada JSON')),
                ('operator_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'axentra_sec_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='¿Está Eliminado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja Lógica')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Edificio')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección Física')),
                ('encargado_sede', models.ForeignKey(blank=True, help_text='Líder técnico responsable del soporte en este edificio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes_tecnicas_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Encargado Técnico de Sede (TI)')),
            ],
            options={
                'verbose_name': 'Sede / Edificio',
                'verbose_name_plural': 'Sedes / Edificios',
                'db_table': 'axentra_org_sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='dependencia',
            name='sedes_ocupadas',
            field=models.ManyToManyField(related_name='dependencias', through='security.AreaOperativa', to='security.sede', verbose_name='Sedes Físicas Operativas'),
        ),
        migrations.AddField(
            model_name='areaoperativa',
            name='sede_fisica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='security.sede', verbose_name='Sede Física de Operación'),
        ),
        migrations.CreateModel(
            name='UserAppRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='¿Está Eliminado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja Lógica')),
                ('role', models.CharField(choices=[('owner', '👑 Dueño / Director General (Acceso Total)'), ('admin', '🔒 Administrador de Módulo'), ('editor', '📝 Editor / Operador / Capturista'), ('reviewer', '👁️ Revisor / Auditor'), ('viewer', '👤 Solo Lectura')], default='viewer', max_length=20, verbose_name='Rol Asignado en el Módulo')),
                ('permissions_list', models.JSONField(blank=True, default=list, help_text='Clonación atómica de privilegios para permitir overrides individuales.', verbose_name='Lista de Permisos Finos (JSON Overrides)')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='security.appmodule', verbose_name='Módulo Autorizado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario Público')),
            ],
            options={
                'verbose_name': 'Permiso de Aplicación',
                'verbose_name_plural': 'Permisos de Aplicaciones',
                'db_table': 'axentra_sec_user_roles',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='¿Está Eliminado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja Lógica')),
                ('puesto', models.CharField(blank=True, help_text='Ej: Jefa de Departamento, Auditor Interno', max_length=100, verbose_name='Puesto del Funcionario')),
                ('telefono_oficina', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Oficina / Extensión')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='security.areaoperativa', verbose_name='Área Operativa / Oficina de Adscripción')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='axentra_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Funcionario',
                'verbose_name_plural': 'Perfiles de Funcionarios',
                'db_table': 'axentra_core_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='AppDependencyCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='¿Está Eliminado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja Lógica')),
                ('can_operate', models.BooleanField(default=False, verbose_name='Puede Operar')),
                ('can_supervise', models.BooleanField(default=False, verbose_name='Puede Supervisar')),
                ('can_authorize', models.BooleanField(default=False, verbose_name='Puede Autorizar')),
                ('custom_settings', models.JSONField(blank=True, default=dict, verbose_name='Configuraciones Avanzadas JSON')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_vinculadas', to='security.appmodule')),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='security.dependencia', verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Capacidad de Dependencia',
                'verbose_name_plural': 'Capacidades de Dependencias',
                'db_table': 'axentra_org_app_capabilities',
                'constraints': [models.UniqueConstraint(fields=('app', 'dependencia'), name='uq_app_dependencia_capability')],
            },
        ),
        migrations.AddConstraint(
            model_name='areaoperativa',
            constraint=models.UniqueConstraint(fields=('dependencia', 'sede_fisica', 'slug'), name='uq_area_dependencia_sede_slug'),
        ),
        migrations.AddConstraint(
            model_name='userapprole',
            constraint=models.UniqueConstraint(fields=('user', 'app'), name='uq_user_app_role'),
        ),
    ]
