# Generated by Django 6.0.6 on 2026-07-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapprole',
            name='permissions_list',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot de permisos finos derivados del rol funcional.', verbose_name='Lista de Permisos Finos'),
        ),
        migrations.AlterField(
            model_name='userapprole',
            name='role',
            field=models.CharField(db_index=True, default='viewer', help_text='Rol declarado en el permissions.py del módulo. Ej: owner, admin, director_rh, sma_manager.', max_length=50, verbose_name='Rol Funcional en el Módulo'),
        ),
    ]
