# Generated by Django 6.0.6 on 2026-06-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
