# Generated by Django 6.0.6 on 2026-07-11 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_userapprole_permissions_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='security.dependencia'),
        ),
    ]
