# Generated by Django 6.0.6 on 2026-06-10 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_sede_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdependencycapability',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='security.dependencia', verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='areaoperativa',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='security.dependencia', verbose_name='Dependencia Superior'),
        ),
        migrations.AlterField(
            model_name='areaoperativa',
            name='sede_fisica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='security.sede', verbose_name='Sede Física de Operación'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='sedes_ocupadas',
            field=models.ManyToManyField(related_name='dependencias', through='security.AreaOperativa', to='security.sede', verbose_name='Sedes Físicas Operativas'),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='operator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Operador del Sistema'),
        ),
        migrations.AlterField(
            model_name='userapprole',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='security.appmodule', verbose_name='Módulo Autorizado'),
        ),
        migrations.AlterField(
            model_name='userapprole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario Público'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='axentra_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
