# Generated by Django 6.0.6 on 2026-06-12 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_appdependencycapability_dependencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityauditlog',
            name='payload_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Telemetría Estructurada JSON'),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario Destino'),
        ),
    ]
