# Generated by Django 6.0.6 on 2026-07-12 21:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_dependencia_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='¿Está Eliminado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja Lógica')),
                ('code', models.CharField(db_index=True, help_text='Clave municipal INEGI/ORFIS. Ejemplo: 039 para Coatzacoalcos.', max_length=3, unique=True, verbose_name='Clave Municipal')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Municipio')),
                ('state_code', models.CharField(blank=True, help_text='Clave INEGI del estado. Veracruz = 30.', max_length=2, verbose_name='Clave del Estado')),
                ('state_name', models.CharField(blank=True, default='VERACRUZ', max_length=120, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'axentra_core_municipalities',
                'ordering': ['state_code', 'code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='dependencia',
            name='codigo_presupuestal',
            field=models.CharField(blank=True, db_index=True, help_text='Código de 3 dígitos usado para folios patrimoniales. Ejemplo: 012.', max_length=3, verbose_name='Código presupuestal'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='security.dependencia', verbose_name='Dependencia superior'),
        ),
        migrations.AddIndex(
            model_name='dependencia',
            index=models.Index(fields=['codigo_presupuestal'], name='axentra_org_codigo__ec7388_idx'),
        ),
        migrations.AddIndex(
            model_name='dependencia',
            index=models.Index(fields=['nombre'], name='axentra_org_nombre_5905dc_idx'),
        ),
        migrations.AddIndex(
            model_name='dependencia',
            index=models.Index(fields=['is_active', 'is_deleted'], name='axentra_org_is_acti_b29865_idx'),
        ),
        migrations.AddIndex(
            model_name='municipality',
            index=models.Index(fields=['code'], name='axentra_cor_code_b04bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='municipality',
            index=models.Index(fields=['name'], name='axentra_cor_name_cf501f_idx'),
        ),
        migrations.AddIndex(
            model_name='municipality',
            index=models.Index(fields=['state_code'], name='axentra_cor_state_c_f90936_idx'),
        ),
        migrations.AddIndex(
            model_name='municipality',
            index=models.Index(fields=['is_active', 'is_deleted'], name='axentra_cor_is_acti_b474a7_idx'),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='municipality',
            field=models.ForeignKey(blank=True, help_text='Municipio oficial asociado a la configuración institucional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_configs', to='security.municipality', verbose_name='Municipio'),
        ),
    ]
