# Generated by Django 6.0.6 on 2026-07-12 22:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_municipality_dependencia_codigo_presupuestal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='¿Está Eliminado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Baja Lógica')),
                ('parameter_type', models.CharField(choices=[('UMA', 'Unidad de Medida y Actualización'), ('MINIMUM_WAGE', 'Salario Mínimo'), ('UPDATE_FACTOR', 'Factor de Actualización'), ('SURCHARGE_RATE', 'Tasa de Recargo'), ('DISCOUNT_RATE', 'Tasa de Descuento'), ('CUSTOM', 'Parámetro Personalizado')], db_index=True, help_text='Tipo de parámetro oficial. Ejemplo: UMA.', max_length=50, verbose_name='Tipo de parámetro')),
                ('year', models.PositiveIntegerField(db_index=True, help_text='Año fiscal o ejercicio aplicable. Ejemplo: 2026.', verbose_name='Año')),
                ('name', models.CharField(help_text='Nombre descriptivo del parámetro. Ejemplo: UMA 2026.', max_length=150, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Código interno opcional. Ejemplo: UMA_2026.', max_length=80, verbose_name='Código interno')),
                ('value', models.DecimalField(decimal_places=4, help_text='Valor numérico del parámetro.', max_digits=14, verbose_name='Valor')),
                ('unit', models.CharField(default='MXN', help_text='Unidad del valor. Ejemplo: MXN, %, FACTOR.', max_length=50, verbose_name='Unidad')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Vigente desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Vigente hasta')),
                ('source', models.CharField(blank=True, help_text='Referencia o fuente oficial del parámetro.', max_length=255, verbose_name='Fuente oficial')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Parámetro oficial',
                'verbose_name_plural': 'Parámetros oficiales',
                'db_table': 'axentra_core_official_parameters',
                'ordering': ['-year', 'parameter_type', 'name'],
                'indexes': [models.Index(fields=['parameter_type'], name='axentra_cor_paramet_7a54d8_idx'), models.Index(fields=['year'], name='axentra_cor_year_d17c2b_idx'), models.Index(fields=['code'], name='axentra_cor_code_7c3f10_idx'), models.Index(fields=['parameter_type', 'year'], name='axentra_cor_paramet_be9c5c_idx'), models.Index(fields=['is_active', 'is_deleted'], name='axentra_cor_is_acti_7761d5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('parameter_type', 'year'), name='uq_official_parameter_type_year_active')],
            },
        ),
    ]
