# Generated by Django 6.0.6 on 2026-06-12 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_securityauditlog_payload_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityauditlog',
            name='app_namespace',
            field=models.CharField(db_index=True, default='core', max_length=50, verbose_name='Módulo / App de Origen'),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, default='127.0.0.1', null=True, verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='search_target',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Criterio / Llave de Búsqueda Dinámica'),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='Navegador / Dispositivo'),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='action_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Acción Ejecutada'),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='level_status',
            field=models.CharField(choices=[('CRITICAL', '🚨 Operación Crítica / Traslape / Bloqueo'), ('SUCCESS', '🟢 Operación Exitosa / Acceso Concedido'), ('INFO', '🔵 Modificación Informativa / Rutina')], db_index=True, default='INFO', max_length=15, verbose_name='Nivel del Evento'),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='target_scope',
            field=models.CharField(max_length=255, verbose_name='Ámbito / Descripción del Destino'),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario Afectado'),
        ),
    ]
