# Generated by Django 6.0.6 on 2026-06-12 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_securityauditlog_app_namespace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityauditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', '➕ ALTA / CREACIÓN'), ('UPDATE', '📝 MODIFICACIÓN / ACTUALIZACIÓN'), ('DELETE', '❌ BAJA / ELIMINACIÓN'), ('ASSIGN', '🔑 ASIGNACIÓN / PRIVILEGIO'), ('ACCESS', '🔓 ACCESO / LOGIN / CONTROL'), ('QUERY', '🔍 CONSULTA / EXTRACCIÓN FORENSE'), ('RESET', '🔒 RESTABLECIMIENTO / LOCKDOWN')], db_index=True, default='UPDATE', max_length=20, verbose_name='Tipo de Acción (Verbo)'),
        ),
        migrations.AddField(
            model_name='securityauditlog',
            name='module_component',
            field=models.CharField(db_index=True, default='GENERAL', max_length=100, verbose_name='Componente / Vista de Origen'),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='action_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Descripción de la Acción'),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='app_namespace',
            field=models.CharField(db_index=True, default='core', max_length=50, verbose_name='Ecosistema / App'),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, default='127.0.0.1', verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='operator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_recibidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
