from .asset_views import (
    asset_directory_options_view,
    asset_audits_view,
    asset_condition_view,
    asset_correct_view,
    asset_custodies_view,
    asset_detail_view,
    asset_disposals_view,
    asset_documents_view,
    asset_extended_record_view,
    asset_financials_view,
    asset_history_view,
    asset_list_view,
    asset_loan_create_view,
    asset_loans_view,
    asset_movements_view,
    asset_photos_view,
    asset_technical_view,
    asset_technical_sheet_view,
)
from .dashboard_views import inventory_dashboard_view
from .custody_document_views import (
    custody_document_close_view,
    custody_document_create_view,
    custody_document_detail_view,
    custody_document_list_view,
    custody_document_print_view,
    custody_document_replace_view,
)
from .catalog_views import (
    catalog_create_view, catalog_deactivate_view, catalog_list_view,
    catalog_update_view,
)
from .help_views import inventory_help_detail_view, inventory_help_view
from .financial_views import (
    accounting_export_create_view,
    accounting_export_download_view,
    depreciation_run_calculate_view,
    depreciation_run_create_view,
    depreciation_run_detail_view,
    depreciation_run_post_view,
    depreciation_policy_list_view,
    depreciation_policy_create_view,
    depreciation_policy_close_view,
    financial_dashboard_view,
    financial_history_view,
    reconciliation_create_view,
    reconciliation_detail_view,
    reconciliation_process_view,
    reconciliation_close_view,
)
from .intake_views import (
    intake_approve_view, intake_cancel_view, intake_create_view,
    intake_directory_areas_view, intake_directory_departments_view,
    intake_directory_users_view, intake_models_view,
    intake_department_decision_view, intake_detail_view, intake_list_view,
    intake_observe_view, intake_register_view, intake_send_to_patrimony_view,
    intake_submit_view,
)
from .registry_views import (
    custody_accept_view, custody_asset_options_view,
    custody_authorize_view, custody_cancel_view,
    custody_complete_return_view, custody_create_view, custody_deliver_view,
    custody_directory_areas_view, custody_directory_departments_view,
    custody_directory_users_view,
    custody_detail_view, custody_list_view, custody_reject_view,
    custody_request_return_view, custody_submit_view, disposal_cancel_view,
    disposal_create_view, disposal_detail_view, disposal_execute_view,
    disposal_finalize_view, disposal_list_view, disposal_resolve_stage_view,
    disposal_stage_document_upload_view, disposal_document_validate_view,
    disposal_submit_view, document_download_view, document_list_view,
    document_upload_view, document_validate_view,
    loan_authorize_view, loan_cancel_view, loan_create_view,
    loan_deliver_view, loan_department_decision_view, loan_detail_view,
    loan_directory_areas_view, loan_directory_assets_view,
    loan_directory_departments_view, loan_directory_users_view,
    loan_list_view, loan_request_return_view, loan_return_view,
    loan_submit_view, movement_create_view,
    movement_destination_decision_view, movement_detail_view,
    movement_directory_options_view, movement_execute_view,
    movement_list_view, movement_origin_decision_view,
    movement_request_detail_view,
    physical_audit_cancel_view, physical_audit_close_view,
    physical_audit_create_view, physical_audit_detail_view,
    physical_audit_directory_areas_view,
    physical_audit_directory_departments_view,
    physical_audit_directory_users_view,
    physical_audit_eligible_assets_view,
    physical_audit_freeze_view, physical_audit_item_reconcile_view,
    physical_audit_list_view, physical_audit_not_found_view,
    physical_audit_pending_not_found_view,
    physical_audit_document_upload_view,
    physical_audit_photo_upload_view,
    physical_audit_report_view,
    physical_audit_reconciliation_view, physical_audit_scan_view,
    physical_audit_start_view, physical_audit_unlisted_view,
)

__all__ = [name for name in globals() if name.endswith("_view")]
