# Generated by Django 6.0.6 on 2026-07-19 04:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='classification_authorized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de autorización de clasificación'),
        ),
        migrations.AddField(
            model_name='asset',
            name='classification_authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_classifications_authorized', to=settings.AUTH_USER_MODEL, verbose_name='Clasificación autorizada por'),
        ),
        migrations.AddField(
            model_name='asset',
            name='classification_override_reason',
            field=models.TextField(blank=True, verbose_name='Justificación de clasificación diferente'),
        ),
        migrations.CreateModel(
            name='InventoryAssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de baja lógica')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código para folio')),
                ('name', models.CharField(max_length=160, verbose_name='Nombre')),
                ('nature', models.CharField(choices=[('MOVABLE', 'Bien Mueble'), ('IMMOVABLE', 'Bien Inmueble'), ('INTANGIBLE', 'Bien Intangible')], max_length=20, verbose_name='Naturaleza')),
                ('is_capitalizable_default', models.BooleanField(default=False, verbose_name='Capitalizable por defecto')),
                ('requires_uma_validation', models.BooleanField(default=False, verbose_name='Requiere validación UMA')),
                ('allows_user_proposal', models.BooleanField(default=True, verbose_name='Disponible como propuesta del capturista')),
                ('requires_override_approval', models.BooleanField(default=True, verbose_name='Exige autorización cuando contradice el cálculo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo patrimonial configurable',
                'verbose_name_plural': 'Tipos patrimoniales configurables',
                'db_table': 'inventory_asset_types',
                'ordering': ['nature', 'code'],
                'indexes': [models.Index(fields=['nature', 'is_active'], name='inventory_a_nature_ab5139_idx'), models.Index(fields=['allows_user_proposal', 'is_active'], name='inventory_a_allows__a2db62_idx')],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='authorized_asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_authorized', to='inventory.inventoryassettype', verbose_name='Tipo patrimonial autorizado'),
        ),
        migrations.AddField(
            model_name='asset',
            name='calculated_asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_calculated', to='inventory.inventoryassettype', verbose_name='Tipo patrimonial calculado'),
        ),
        migrations.AddField(
            model_name='assetintakerequest',
            name='proposed_asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_requests_proposed', to='inventory.inventoryassettype', verbose_name='Tipo patrimonial propuesto'),
        ),
    ]
