# Generated by Django 6.0.6 on 2026-07-12 20:26

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('security', '0003_dependencia_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryFolioSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('municipality_code', models.CharField(max_length=3, verbose_name='Clave municipal')),
                ('year', models.PositiveSmallIntegerField(help_text='Ejemplo: 26 para 2026.', verbose_name='Año corto')),
                ('conac_code', models.CharField(max_length=10, verbose_name='Código CONAC / COG')),
                ('dependency_code', models.CharField(max_length=10, verbose_name='Código presupuestal de dependencia')),
                ('asset_type_code', models.CharField(help_text='BM, BI, BP, etc.', max_length=2, verbose_name='Tipo de bien')),
                ('current_number', models.PositiveIntegerField(default=0, verbose_name='Consecutivo actual')),
            ],
            options={
                'verbose_name': 'Secuencia de folio',
                'verbose_name_plural': 'Secuencias de folios',
                'db_table': 'inventory_folio_sequences',
                'ordering': ['municipality_code', 'year', 'conac_code', 'dependency_code', 'asset_type_code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='assetrelation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='assetrelation',
            name='child_asset',
        ),
        migrations.RemoveField(
            model_name='assetrelation',
            name='parent_asset',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='consumablemovement',
            name='consumable',
        ),
        migrations.RemoveField(
            model_name='consumablemovement',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='consumablemovement',
            name='related_asset',
        ),
        migrations.RemoveIndex(
            model_name='technicalassetprofile',
            name='inventory_t_technic_f29172_idx',
        ),
        migrations.RemoveIndex(
            model_name='technicalassetprofile',
            name='inventory_t_hostnam_c63e51_idx',
        ),
        migrations.RemoveIndex(
            model_name='technicalassetprofile',
            name='inventory_t_ip_addr_0429ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='technicalassetprofile',
            name='inventory_t_mac_add_d33f67_idx',
        ),
        migrations.AlterModelOptions(
            name='accountingaccount',
            options={'ordering': ['code'], 'verbose_name': 'Cuenta contable', 'verbose_name_plural': 'Cuentas contables'},
        ),
        migrations.AlterModelOptions(
            name='accountingexportbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lote de exportación contable', 'verbose_name_plural': 'Lotes de exportación contable'},
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activo patrimonial', 'verbose_name_plural': 'Activos patrimoniales'},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['nature', 'name'], 'verbose_name': 'Categoría patrimonial', 'verbose_name_plural': 'Categorías patrimoniales'},
        ),
        migrations.AlterModelOptions(
            name='assetmodel',
            options={'ordering': ['manufacturer__name', 'name'], 'verbose_name': 'Modelo de activo', 'verbose_name_plural': 'Modelos de activos'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-fecha_inicio', 'numero_contrato'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='custodyassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Resguardo', 'verbose_name_plural': 'Resguardos'},
        ),
        migrations.AlterModelOptions(
            name='depreciationpolicy',
            options={'ordering': ['name'], 'verbose_name': 'Política de depreciación', 'verbose_name_plural': 'Políticas de depreciación'},
        ),
        migrations.AlterModelOptions(
            name='depreciationrecord',
            options={'ordering': ['-period_year', '-period_month'], 'verbose_name': 'Registro de depreciación', 'verbose_name_plural': 'Registros de depreciación'},
        ),
        migrations.AlterModelOptions(
            name='disposalrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Expediente de baja', 'verbose_name_plural': 'Expedientes de baja'},
        ),
        migrations.AlterModelOptions(
            name='immovableassetdetail',
            options={'verbose_name': 'Detalle de inmueble', 'verbose_name_plural': 'Detalles de inmuebles'},
        ),
        migrations.AlterModelOptions(
            name='inventoryauditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bitácora de inventario', 'verbose_name_plural': 'Bitácora de inventario'},
        ),
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimiento patrimonial', 'verbose_name_plural': 'Movimientos patrimoniales'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'Fabricante', 'verbose_name_plural': 'Fabricantes'},
        ),
        migrations.AlterModelOptions(
            name='physicalaudititem',
            options={'ordering': ['-scanned_at'], 'verbose_name': 'Lectura de auditoría física', 'verbose_name_plural': 'Lecturas de auditoría física'},
        ),
        migrations.AlterModelOptions(
            name='physicalauditsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Auditoría física', 'verbose_name_plural': 'Auditorías físicas'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['razon_social'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='inventory_a_invento_cd82e3_idx',
        ),
        migrations.AddField(
            model_name='asset',
            name='internal_inventory_number',
            field=models.CharField(blank=True, help_text='Folio operativo interno. Ej: AXN-INV-2026-000001.', max_length=80, null=True, unique=True, verbose_name='Folio interno Axentra'),
        ),
        migrations.AddField(
            model_name='asset',
            name='official_inventory_number',
            field=models.CharField(blank=True, help_text='Folio estructurado para ORFIS / SIGMAVER. Ej: 039-26-5151-012-BM-0005.', max_length=80, null=True, unique=True, verbose_name='Folio oficial patrimonial'),
        ),
        migrations.AddField(
            model_name='disposalrequest',
            name='source_app',
            field=models.CharField(blank=True, help_text='Ejemplo: innovation, workflows, helpdesk.', max_length=80, verbose_name='App origen'),
        ),
        migrations.AddField(
            model_name='disposalrequest',
            name='source_model',
            field=models.CharField(blank=True, help_text='Ejemplo: TechnicalOpinion, DisposalWorkflow.', max_length=120, verbose_name='Modelo origen'),
        ),
        migrations.AddField(
            model_name='disposalrequest',
            name='source_object_id',
            field=models.CharField(blank=True, help_text='UUID o identificador del registro origen.', max_length=120, verbose_name='ID objeto origen'),
        ),
        migrations.AlterField(
            model_name='accountingaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='accountingaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='accountingaccount',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='accountingaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='accountingexportbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='accountingexportbatch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='accountingexportbatch',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='accountingexportbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='control_type',
            field=models.CharField(choices=[('CAPITALIZED_ASSET', 'Activo Fijo Capitalizado'), ('INTERNAL_CONTROL', 'Control Interno')], default='INTERNAL_CONTROL', max_length=30, verbose_name='Tipo de control'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='legacy_inventory_number',
            field=models.CharField(blank=True, help_text='Folio previo o heredado durante una migración.', max_length=80, verbose_name='Número de inventario anterior'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='assetdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='assetdocument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='assetdocument',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='assetdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='assetphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='assetphoto',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='assetphoto',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='assetphoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='custodyassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='custodyassignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='custodyassignment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='custodyassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='depreciationpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='depreciationpolicy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='depreciationpolicy',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='depreciationpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='depreciationrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='depreciationrecord',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='depreciationrecord',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='depreciationrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='disposalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='disposalrequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='disposalrequest',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='disposalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='immovableassetdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='immovableassetdetail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='immovableassetdetail',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='immovableassetdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='inventoryauditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='inventoryauditlog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='inventoryauditlog',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='inventoryauditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot auditable del movimiento. No usar como fuente primaria de reglas.', verbose_name='Payload de movimiento'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='reference_folio',
            field=models.CharField(blank=True, help_text='Folio de resguardo, baja, oficio, solicitud o expediente relacionado.', max_length=120, verbose_name='Folio de referencia'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='physicalaudititem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='physicalaudititem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='physicalaudititem',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='physicalaudititem',
            name='scanned_inventory_number',
            field=models.CharField(blank=True, help_text='Puede ser folio oficial, folio interno, folio anterior, QR o código de barras.', max_length=100, verbose_name='Número escaneado'),
        ),
        migrations.AlterField(
            model_name='physicalaudititem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='physicalauditsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='physicalauditsession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='physicalauditsession',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='physicalauditsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AddIndex(
            model_name='accountingaccount',
            index=models.Index(fields=['code'], name='inventory_a_code_86b80c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingaccount',
            index=models.Index(fields=['name'], name='inventory_a_name_3dcfc0_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingaccount',
            index=models.Index(fields=['category'], name='inventory_a_categor_23a793_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingaccount',
            index=models.Index(fields=['is_depreciable'], name='inventory_a_is_depr_461bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingaccount',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_a_is_acti_60986d_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingexportbatch',
            index=models.Index(fields=['export_type'], name='inventory_a_export__05588c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingexportbatch',
            index=models.Index(fields=['period_start'], name='inventory_a_period__835b35_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingexportbatch',
            index=models.Index(fields=['period_end'], name='inventory_a_period__1a7f40_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingexportbatch',
            index=models.Index(fields=['generated_by'], name='inventory_a_generat_0140bd_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingexportbatch',
            index=models.Index(fields=['created_at'], name='inventory_a_created_c7dace_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingexportbatch',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_a_is_acti_ea549a_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['official_inventory_number'], name='inventory_a_officia_6b01d9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['internal_inventory_number'], name='inventory_a_interna_2a0e51_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['legacy_inventory_number'], name='inventory_a_legacy__a7826c_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['code'], name='inventory_a_code_2bc17b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['name'], name='inventory_a_name_9eaa96_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['nature'], name='inventory_a_nature_ba0517_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_a_is_acti_532e12_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmodel',
            index=models.Index(fields=['manufacturer'], name='inventory_a_manufac_69f3db_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmodel',
            index=models.Index(fields=['name'], name='inventory_a_name_361db0_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmodel',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_a_is_acti_de492c_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['numero_contrato'], name='inventory_c_numero__8b876c_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['nombre'], name='inventory_c_nombre_68954d_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['supplier'], name='inventory_c_supplie_caada2_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['fecha_inicio'], name='inventory_c_fecha_i_aef713_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['fecha_fin'], name='inventory_c_fecha_f_15349e_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_c_is_acti_8e51b8_idx'),
        ),
        migrations.AddIndex(
            model_name='custodyassignment',
            index=models.Index(fields=['asset'], name='inventory_c_asset_i_7d5ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='custodyassignment',
            index=models.Index(fields=['assigned_by'], name='inventory_c_assigne_328692_idx'),
        ),
        migrations.AddIndex(
            model_name='custodyassignment',
            index=models.Index(fields=['dependencia'], name='inventory_c_depende_41db64_idx'),
        ),
        migrations.AddIndex(
            model_name='custodyassignment',
            index=models.Index(fields=['area'], name='inventory_c_area_id_a2438a_idx'),
        ),
        migrations.AddIndex(
            model_name='custodyassignment',
            index=models.Index(fields=['sede'], name='inventory_c_sede_id_ed7f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='custodyassignment',
            index=models.Index(fields=['assigned_at'], name='inventory_c_assigne_5d9979_idx'),
        ),
        migrations.AddIndex(
            model_name='custodyassignment',
            index=models.Index(fields=['signed_at'], name='inventory_c_signed__507997_idx'),
        ),
        migrations.AddIndex(
            model_name='custodyassignment',
            index=models.Index(fields=['returned_at'], name='inventory_c_returne_bca07f_idx'),
        ),
        migrations.AddIndex(
            model_name='custodyassignment',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_c_is_acti_4d5c96_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationpolicy',
            index=models.Index(fields=['name'], name='inventory_d_name_550ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationpolicy',
            index=models.Index(fields=['accounting_account'], name='inventory_d_account_3aef8b_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationpolicy',
            index=models.Index(fields=['method'], name='inventory_d_method_564509_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationpolicy',
            index=models.Index(fields=['frequency'], name='inventory_d_frequen_07b72c_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationpolicy',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_d_is_acti_ae0cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationrecord',
            index=models.Index(fields=['asset'], name='inventory_d_asset_i_eda453_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationrecord',
            index=models.Index(fields=['policy'], name='inventory_d_policy__632927_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationrecord',
            index=models.Index(fields=['calculated_by'], name='inventory_d_calcula_793285_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationrecord',
            index=models.Index(fields=['calculated_at'], name='inventory_d_calcula_bdd202_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationrecord',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_d_is_acti_9aeab4_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalrequest',
            index=models.Index(fields=['asset'], name='inventory_d_asset_i_0c8b54_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalrequest',
            index=models.Index(fields=['requested_by'], name='inventory_d_request_63d3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalrequest',
            index=models.Index(fields=['reviewed_by'], name='inventory_d_reviewe_5377bd_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalrequest',
            index=models.Index(fields=['approved_by'], name='inventory_d_approve_cff6be_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalrequest',
            index=models.Index(fields=['requested_at'], name='inventory_d_request_2e87ac_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalrequest',
            index=models.Index(fields=['reviewed_at'], name='inventory_d_reviewe_3eb78e_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalrequest',
            index=models.Index(fields=['approved_at'], name='inventory_d_approve_e0d5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalrequest',
            index=models.Index(fields=['executed_at'], name='inventory_d_execute_4e4c39_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalrequest',
            index=models.Index(fields=['source_app', 'source_model', 'source_object_id'], name='inventory_d_source__a93ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='disposalrequest',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_d_is_acti_13c851_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditlog',
            index=models.Index(fields=['asset'], name='inventory_a_asset_i_03f988_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditlog',
            index=models.Index(fields=['actor'], name='inventory_a_actor_i_9b7ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditlog',
            index=models.Index(fields=['created_at'], name='inventory_a_created_4300ac_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['asset'], name='inventory_a_asset_i_32be4b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['from_dependencia'], name='inventory_a_from_de_abdafb_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['to_dependencia'], name='inventory_a_to_depe_d71aca_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['from_area'], name='inventory_a_from_ar_a03698_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['to_area'], name='inventory_a_to_area_d7082e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['from_sede'], name='inventory_a_from_se_76944b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['to_sede'], name='inventory_a_to_sede_598162_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['from_user'], name='inventory_a_from_us_3d167d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['to_user'], name='inventory_a_to_user_fcf220_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['performed_by'], name='inventory_a_perform_9e27bf_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['created_at'], name='inventory_a_created_9e5bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_a_is_acti_884970_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['name'], name='inventory_m_name_2b7252_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_m_is_acti_d547ac_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalaudititem',
            index=models.Index(fields=['session'], name='inventory_p_session_b21ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalaudititem',
            index=models.Index(fields=['asset'], name='inventory_p_asset_i_6958d1_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalaudititem',
            index=models.Index(fields=['scanned_inventory_number'], name='inventory_p_scanned_6d3e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalaudititem',
            index=models.Index(fields=['result'], name='inventory_p_result_6b4382_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalaudititem',
            index=models.Index(fields=['scanned_by'], name='inventory_p_scanned_8e3fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalaudititem',
            index=models.Index(fields=['scanned_at'], name='inventory_p_scanned_b3380a_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalauditsession',
            index=models.Index(fields=['folio'], name='inventory_p_folio_1b5588_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalauditsession',
            index=models.Index(fields=['status'], name='inventory_p_status_6a7d77_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalauditsession',
            index=models.Index(fields=['sede'], name='inventory_p_sede_id_fc2334_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalauditsession',
            index=models.Index(fields=['dependencia'], name='inventory_p_depende_0f2d77_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalauditsession',
            index=models.Index(fields=['area'], name='inventory_p_area_id_f7ee0a_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalauditsession',
            index=models.Index(fields=['started_at'], name='inventory_p_started_bcab23_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalauditsession',
            index=models.Index(fields=['closed_at'], name='inventory_p_closed__102840_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['razon_social'], name='inventory_s_razon_s_5f3c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['rfc'], name='inventory_s_rfc_073eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['email'], name='inventory_s_email_fd3fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_s_is_acti_dd7588_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryfoliosequence',
            index=models.Index(fields=['municipality_code', 'year', 'conac_code', 'dependency_code', 'asset_type_code'], name='inventory_f_municip_639492_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryfoliosequence',
            constraint=models.UniqueConstraint(fields=('municipality_code', 'year', 'conac_code', 'dependency_code', 'asset_type_code'), name='uq_inventory_folio_sequence_scope'),
        ),
        migrations.DeleteModel(
            name='AssetRelation',
        ),
        migrations.DeleteModel(
            name='Consumable',
        ),
        migrations.DeleteModel(
            name='ConsumableMovement',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='inventory_number',
        ),
        migrations.DeleteModel(
            name='TechnicalAssetProfile',
        ),
    ]
