# Generated by Django 6.0.6 on 2026-07-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_disposal_stage_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='authorized_asset_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='calculated_asset_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='classification_authorized_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='classification_authorized_by',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='classification_override_reason',
        ),
        migrations.RemoveField(
            model_name='assetintakerequest',
            name='proposed_asset_type',
        ),
    ]
