# apps/inventory/integrations/__init__.py

from apps.inventory.integrations.contracts import (
    AreaContext,
    DepartmentApprovalAuthority,
    DepartmentCapabilityIdentity,
    DepartmentIdentity,
    ExternalAssetActivity,
    ExternalAssetActivityCollection,
    ModuleRoleIdentity,
    MunicipalityIdentity,
    SiteIdentity,
    TenantIdentity,
    UserIdentity,
    UserOrganizationalContext,
)

from apps.inventory.integrations.core_directory import (
    CoreDirectoryError,
    DirectoryEntityNotFound,
    InvalidDirectoryIdentifier,
    OrganizationalContextError,
    get_active_tenant,
    get_area_context,
    get_department,
    get_department_capability,
    get_module_role,
    get_site,
    get_user_identity,
    get_user_organizational_context,
    list_areas,
    list_departments,
    list_department_approvers,
    list_sites,
    list_users,
    user_belongs_to_department,
    user_can_approve_department,
    user_can_manage_inventory,
    validate_organizational_context,
)
from apps.inventory.integrations.external_asset_activity import (
    get_external_asset_activity,
)

__all__ = [
    "AreaContext",
    "CoreDirectoryError",
    "DepartmentApprovalAuthority",
    "DepartmentCapabilityIdentity",
    "DepartmentIdentity",
    "DirectoryEntityNotFound",
    "ExternalAssetActivity",
    "ExternalAssetActivityCollection",
    "InvalidDirectoryIdentifier",
    "ModuleRoleIdentity",
    "MunicipalityIdentity",
    "OrganizationalContextError",
    "SiteIdentity",
    "TenantIdentity",
    "UserIdentity",
    "UserOrganizationalContext",
    "get_active_tenant",
    "get_external_asset_activity",
    "get_area_context",
    "get_department",
    "get_department_capability",
    "get_module_role",
    "get_site",
    "get_user_identity",
    "get_user_organizational_context",
    "list_areas",
    "list_departments",
    "list_department_approvers",
    "list_sites",
    "list_users",
    "user_belongs_to_department",
    "user_can_approve_department",
    "user_can_manage_inventory",
    "validate_organizational_context",
]
